version: '3.8'

services:
  roboconnect:
    image: roboconnect
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn roboconnect.api:api --host 0.0.0.0 --port 8080 --root-path ${ROOT_PATH:-/}
    ports:
      - ${PORT:-8080}:8080
    environment:
      - API_KEY=${API_KEY}
