version: '3.8'

services:
  robocon:
    image: robocon
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.api:api --host 0.0.0.0 --port 8080 --root-path ${API_ROOT_PATH:-/}
    ports:
      - ${API_HOST:-0.0.0.0}:${API_PORT:-8080}:8080
    environment:
      - API_KEY=${API_KEY}
      - API_ROOT_PATH=${API_ROOT_PATH}
